### ISSUE TITLE
The sorting results are not restored when keywords are deleted.

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [pacocoursey/cmdk#264]
Based on the behavior of Raycast, the sorting results should return to the initial order when all keywords are deleted, but there is a problem where they do not return.

![2024-05-22 00 41 21](https://github.com/pacocoursey/cmdk/assets/15520015/15be3129-2708-4e6a-a5fd-0057e6b0063c)

**Comment by gabrielgatu** [comment]
Would love to see this fixed, apparently the only solution to this bug for now is to roll a manual filter&sort implementation by setting `shouldFilter` to `false`.

**Comment by sharathprabhal** [comment]
Bumping this.

**Comment by giraffesyo** [comment]
This seems like it's probably a duplicate of https://github.com/pacocoursey/cmdk/issues/161. I was able to workaround this by doing what they said in the other post, i.e. putting the ungrouped items into a group with no header, which causes the sorting to work properly. Example:

```typescript
interface IPageProps {
  // setPages: React.Dispatch<React.SetStateAction<string[]>>
  // setOpen: React.Dispatch<React.SetStateAction<boolean>>
  handleNavigation: (item: {
    name?: string
    cmdKPage?: boolean
    href?: string
  }) => void
}

export function RootPage({ handleNavigation }: IPageProps) {
  return navigation.map(item => {
    if (item.items) {
      return (
        <React.Fragment key={item.name}>
          <Command.Group heading={item.name}>
            {item.items.map(subItem => (
              <Command.Item
                value={`${item.name}-${subItem.name}`}
                key={`${item.name}-${subItem.name}`}
                onSelect={() => handleNavigation(subItem)}
              >
                {subItem.Icon && <subItem.Icon className='w-4 h-4 mr-2' />}
                {subItem.name}
              </Command.Item>
            ))}
          </Command.Group>
          <Command.Separator />
        </React.Fragment>
      )
    } else {
      return (
        <Command.Group key={item.name}>
          <Command.Item
            value={item.name}
            onSelect={() => handleNavigation(item)}
          >
            {item.Icon && <item.Icon className='w-4 h-4 mr-2' />}
            {item.name}
          </Command.Item>
        </Command.Group>
      )
    }
  })
}
```

**Comment by goranchristian** [comment]
When using non-text elements such as icons in the commandItem, the filter functionality does not work as it should it seems. A workaround was indeed adding a manual filtering and disabling the built in one. But in the raycast example there are icons...?

**Comment by Mr-Vipi** [comment]
Same issue here

**Comment by grundmanise** [comment]
@basaran, thanks, while not a fix, that works as an interim solution

**Comment by ruriarte-zaelot** [comment]
I implemented a custom filter fn, otherwise the list is unusable because for some reason the it is completely disordered after you use the search feature.

**Comment by webbiffy** [comment]
The issue still happening.

For now, I've set it up so the state updates as the user types and then value is empty so only when user clear all the search input text. Also I added a debounce so it doesn't fire too often.

First declare and define the reset function:

```
  const listRef = useRef<HTMLDivElement>(null)
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const [key, setKey] = useState<number>(0)
  const [isResetting, setIsResetting] = useState(false)

  useEffect(() => {
    return () => {
      if (debounceRef.current) clearTimeout(debounceRef.current)
    }
  }, [])

  const handleSearchChange = useCallback((value: string) => {
    listRef.current?.scrollTo({ top: 0, behavior: "smooth" })
    if (value === "") {
      setIsResetting(true)
      if (debounceRef.current) clearTimeout(debounceRef.current)
      debounceRef.current = setTimeout(() => {
        setKey((p) => p + 1)
        setIsResetting(false)
      }, 300)
    }
  }, [])
```


Then add pass it on the onValueChange prop of CommandInput like:
```
<Command>
<CommandInput
     placeholder={`Search ${searchLabel}...`}
     onValueChange={debouncedResetList}
 />

<CommandList ref={listRef} key={key}>
      {!isLoading && !isResetting && (
         <CommandEmpty>No {label} found.</CommandEmpty>
       }
   <CommandGroup>
       {isLoading || isResetting
                        ? (skeletonLoader ?? <DefaultComboBoxSkeleton />)
                        : items.map((option) => (
                            <CommandItem
                              value={option.name || String(option.id)}
                              key={option.id}
                              keywords={option.keywords}
                              onSelect={() => {
                                // if you have any code you want on select, like if you want to save it to the react hook form onChange
                              }}
                            >
                              {option.content ?? option.name}
                            </CommandItem>
            ))}
   </CommandGroup>
</Command>
```
